[package]
name = "xiv-crafting-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = {version = "0.2.78", features = ["serde-serialize"]}
serde = {version = "1.0.131", features = ["derive"]}
genevo = {verison = "0.7", features = ["smallvec"]}
smallvec = "1.7.0"