[package]
name = "xiv-crafting-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"
codegen-units = 1
lto = true

[dependencies]
wasm-bindgen = {version = "0.2.78", features = ["serde-serialize"]}
serde = {version = "1.0.131", features = ["derive"]}
genevo = {verison = "0.7", features = ["smallvec", "wasm-bindgen"]}
smallvec = "1.7.0"
console_error_panic_hook = "0.1.7"
serde_json = "1.0.73"