[package]
name = "xiv-crafting-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = true

[profile.bench]
debug = true

[dependencies]
wasm-bindgen = {version = "0.2.78", features = ["serde-serialize"]}
serde = {version = "1.0.131", features = ["derive"]}
genevo = {version = "0.7", features = ["smallvec", "wasm-bindgen"]}
smallvec = "1.7.0"
console_error_panic_hook = "0.1.7"
serde_json = "1.0.73"

[dev-dependencies]
criterion = "0.3"
rand = {version = "0.8.4", features = ["small_rng"]}

[[bench]]
name = "fitness"
harness = false

[[bench]]
name = "simulator"
harness = false
